<?php

namespace Kitpages\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderLineRepository extends EntityRepository
{
}